In [ ]:
import pandas as pd

elections = pd.read_csv('elections.csv')

In [17]:
elections.head()

,Year,Candidate,Party,Popular vote,Result,%
0,1824,Andrew Jackson,Democratic-Republican,151271,loss,57.210122
1,1824,John Quincy Adams,Democratic-Republican,113142,win,42.789878
2,1828,Andrew Jackson,Democratic,642806,win,56.203927
3,1828,John Quincy Adams,National Republican,500897,loss,43.796073
4,1832,Andrew Jackson,Democratic,702735,win,54.574789

In [13]:
elections.tail()

     Year       Candidate              Party  Popular vote Result          %
182  2024    Donald Trump         Republican      77303568    win  49.808629
183  2024   Kamala Harris         Democratic      75019230   loss  48.336772
184  2024      Jill Stein              Green        861155   loss   0.554864
185  2024  Robert Kennedy        Independent        756383   loss   0.487357
186  2024    Chase Oliver  Libertarian Party        650130   loss   0.418895

In [14]:
elections.info()

<class 'pandas.DataFrame'>
RangeIndex: 187 entries, 0 to 186
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Year          187 non-null    int64
 1   Candidate     187 non-null    str
 2   Party         187 non-null    str
 3   Popular vote  187 non-null    int64
 4   Result        187 non-null    str
 5   %             187 non-null    float64
dtypes: float64(1), int64(2), str(3)
memory usage: 8.9 KB